concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
queues:
  - [scheduled, 10]
  - [market_data, 5]
  - [high_priority, 4]
  - [medium_priority, 2]
  - [maintenance, 2]
  - [low_priority, 1]
  - [default, 1]

:schedule:
  process_deletions:
    cron: '*/30 * * * *'
    class: CheckDeletionsJob
    description: 'Process scheduled account deletions'
